name: "Auto Deployment"
description: "Deploy Firebase using Github"
inputs:
  properties-name: # id of input
    description: "property name to extract its value from package.json"
    required: true
    default: 'version,version_staging'

outputs:
  property: # id of output
    description: "property value"
runs:
  using: "node16"
  main: "dist/index.js"